MODEL_2D:
  TYPE: "UNetResNet34"
MODEL_3D:
  TYPE: "SCN"
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    preprocess_dir: "mopa/datasets/nuscenes/preprocess_obj/preprocess"
    nuscenes_dir: "mopa/datasets/nuscenes"  # only front cam images are needed
    label_mode: "object"
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    preprocess_dir: "mopa/datasets/nuscenes/preprocess_obj/preprocess"
    nuscenes_dir: "mopa/datasets/nuscenes"  # only front cam images are needed
    augmentation:
      rot_z: 0.0
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  MODEL_2D:
    TYPE: "Adam"
    BASE_LR: 0.001
  MODEL_3D:
    TYPE: "Adam"
    BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
VAL:
  BATCH_SIZE: 32
  PERIOD: 5000
OUTPUT_DIR: "mopa/exp"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/mopa