MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 5
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 5
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    preprocess_dir: "mopa/datasets/nuscenes/preprocess_obj/preprocess"
    nuscenes_dir: "mopa/datasets/nuscenes"  # only front cam images are needed
    label_mode: "object"
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    preprocess_dir: "mopa/datasets/nuscenes/preprocess_obj/preprocess"
    nuscenes_dir: "mopa/datasets/nuscenes"  # only front cam images are needed
    label_mode: "object"
    ps_label_dir: "ps_label/0713_usa_singapore"
    use_pc_mm: True
    obj_name_ls: ["person", "bicycle", "motorcycle"]
    # obj_name_ls: ["truck"]
    obj_root_dir: "mopa/datasets/waymo/waymo_extracted/objects"
    sam_mask_dir: "img_mask"
    g_indices_dir: 'g_indices'
    ema_input: True
    # augmentation:
    #   rot_z: 0.0
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  MODEL_2D:
    TYPE: "Adam"
    BASE_LR: 0.001
  MODEL_3D:
    TYPE: "Adam"
    BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.47956584, 4.26788384, 5.71114131, 3.80241668, 1.]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
    lambda_pl: 1.0
  PC_MM:
    z_disc: 0.3
    insert_mode: "ground"
    search_voxel_size: 0.5
    lambda_pc_mm: 1.0
    lambda_ctr_src: 0.0
    lambda_ctr_trg: 0.0
    lambda_sam_cons: 0.01
    use_proj: True
    dis_range: (0, 15)
    proj_W: 1080
    proj_H: 32
    fov_up: 0.17453
    fov_down: -0.52360
    ema_start_iter: 60000
    ema_alpha_teacher: 0.999
    ema_update_period: 1
    ema_xm_prob: 0.9
    use_class_weights: True
VAL:
  BATCH_SIZE: 32
  PERIOD: 5000
OUTPUT_DIR: "mopa/exp"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/mopa
