MODEL_2D:
  TYPE: "UNetResNet34"
  NUM_CLASSES: 5
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  NUM_CLASSES: 5
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    preprocess_dir: "mopa/datasets/nuscenes/preprocess_obj/preprocess"
    nuscenes_dir: "mopa/datasets/nuscenes"  # only front cam images are needed
    label_mode: "object"
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    preprocess_dir: "mopa/datasets/nuscenes/preprocess_obj/preprocess"
    nuscenes_dir: "mopa/datasets/nuscenes"  # only front cam images are needed
    augmentation:
      rot_z: 0.0
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  MODEL_2D:
    TYPE: "Adam"
    BASE_LR: 0.001
  MODEL_3D:
    TYPE: "Adam"
    BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.47956584, 4.26788384, 5.71114131, 3.80241668, 1.]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
VAL:
  BATCH_SIZE: 32
  PERIOD: 5000
OUTPUT_DIR: "mopa/exp"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/mopa
